### ISSUE TITLE
README example fails to run on WINE

### ISSUE THREAD

**Issue by apprehensions** [rodrigocfd/windigo#29]
```
$ GOOS=windows go build                                    
$ wine limejuice.exe    
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0024:fixme:seh:WerGetFlags (FFFFFFFFFFFFFFFF, 00007FFFFE2FFED8) stub
0024:fixme:seh:WerSetFlags (32) stub
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
0024:fixme:powrprof:PowerRegisterSuspendResumeNotification (0x00000002,00007FFFFE2FFE48,00007FFFFE2FFE40) stub!
panic: [87 0x57] Invalid parameter.

goroutine 1 [running, locked to thread]:
github.com/rodrigocfd/windigo/ui._FirstMainStuff()
        /home/meow/.cache/go/mod/github.com/rodrigocfd/windigo@v0.0.0-20230809154420-8faa606d9f5f/ui/any_gl
obals.go:175 +0x5c
github.com/rodrigocfd/windigo/ui.(*_WindowRawMain).RunAsMain(0xc000114000)
        /home/meow/.cache/go/mod/github.com/rodrigocfd/windigo@v0.0.0-20230809154420-8faa606d9f5f/ui/Window
RawMain.go:49 +0x45
main.main()
        /home/meow/src/test/main.go:16 +0x25
```

**Comment by Hoto-Cocoa** [comment]
In past, I was tried run application that used windigo on Wine, but I faced some error.

That's caused by Wine's incorrect implementation. At my try, https://bugs.winehq.org/show_bug.cgi?id=54951 is the issue.

**Comment by apprehensions** [comment]
Works!

![Image](https://github.com/user-attachments/assets/1e533fcc-04d9-41b6-ae48-053519bdb04d)
